
class globals:
    SECTION_TITLE_KEY = "SECTION_TITLE"
    CRITICAL_KEY = "CRITICAL"
    SECTION_META_INFO = [SECTION_TITLE_KEY, CRITICAL_KEY]
    SECTIONS_KEY = "SECTIONS"
    SECTION_ITEMS_KEY = "SECTION_ITEMS"
    HANDLEBARS_FALSE = "false"
    LOCATION_DETAILS_KEY = "LOCATION_DETAILS"
